export const PLANS = [
  {
    code: "SOLO",
    name: "Solo",
    tagline: "For the independent optometrist",
    priceMonthlyUsd: 29,
    priceYearlyUsd: 290,
    maxBranches: 1,
    maxUsers: 3,
    monthlyMessages: 300,
    sortOrder: 1,
    features: [
      "1 branch, up to 3 staff logins",
      "Patient records & digital prescriptions",
      "Orders, job cards & lab tracking",
      "Receipts, expenses & full double-entry books",
      "USD & ZWG multi-currency",
      "300 SMS/WhatsApp reminders per month",
      "Email support",
    ],
  },
  {
    code: "PRACTICE",
    name: "Practice",
    tagline: "For busy practices that want to grow",
    priceMonthlyUsd: 69,
    priceYearlyUsd: 690,
    maxBranches: 3,
    maxUsers: 12,
    monthlyMessages: 1500,
    sortOrder: 2,
    features: [
      "Up to 3 branches, 12 staff logins",
      "Everything in Solo",
      "Medical aid pre-auth & claims tracking",
      "Frame & lens inventory with stock transfers",
      "Automated 2-year recall campaigns",
      "Asset register & depreciation",
      "1,500 SMS/WhatsApp reminders per month",
      "Priority WhatsApp support",
    ],
  },
  {
    code: "GROUP",
    name: "Group",
    tagline: "For optical chains & franchise groups",
    priceMonthlyUsd: 159,
    priceYearlyUsd: 1590,
    maxBranches: 0,
    maxUsers: 0,
    monthlyMessages: 5000,
    sortOrder: 3,
    features: [
      "Unlimited branches & staff",
      "Everything in Practice",
      "Consolidated & per-branch financials",
      "Role-based access & audit trail",
      "Custom SMS sender ID",
      "5,000 SMS/WhatsApp reminders per month",
      "Dedicated onboarding & data migration",
    ],
  },
];
