import "server-only";
import ExcelJS from "exceljs";
import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";
import type { Statement, StatementRow } from "./statements";

type Header = { orgName: string; generatedBy: string };

const fmt = (n: number) => (n < 0 ? "(" : "") + Math.abs(n).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) + (n < 0 ? ")" : "");

function cellText(s: Statement, row: StatementRow, i: number) {
  const v = row.cells[i];
  if (v === null || v === undefined) return "";
  if (typeof v === "number") return s.columns[i]?.money ? fmt(v) : String(v);
  return v;
}

export function toCsv(s: Statement, h: Header) {
  const esc = (v: string) => (/[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v);
  const out: string[][] = [[h.orgName], [s.title], [s.subtitle], []];
  if (s.columns.some((c) => c.label)) out.push(s.columns.map((c) => c.label));
  for (const r of s.rows) out.push(r.cells.map((c, i) => (c === null ? "" : typeof c === "number" ? (s.columns[i]?.money ? c.toFixed(2) : String(c)) : (r.indent && i === 0 ? "  " : "") + c)));
  if (s.notes?.length) out.push([], ...s.notes.map((n) => [n]));
  return out.map((r) => r.map(esc).join(",")).join("\r\n");
}

export async function toXlsx(s: Statement, h: Header) {
  const wb = new ExcelJS.Workbook();
  wb.creator = "OptiVault";
  wb.created = new Date();
  const ws = wb.addWorksheet(s.title.slice(0, 31), { views: [{ showGridLines: false }], pageSetup: { orientation: s.orientation ?? "portrait", fitToPage: true, fitToWidth: 1, fitToHeight: 0 } });
  const n = s.columns.length;
  const widths = s.columns.map((c, i) => c.width ?? (i === 0 ? 52 : 18));
  ws.columns = widths.map((w) => ({ width: w }));

  const title = (text: string, size: number, bold: boolean, color = "FF0F172A") => {
    const r = ws.addRow([text]);
    ws.mergeCells(r.number, 1, r.number, n);
    r.font = { size, bold, color: { argb: color } };
  };
  title(h.orgName, 14, true);
  title(s.title, 12, true, "FF0E7490");
  title(s.subtitle, 10, false, "FF64748B");
  ws.addRow([]);
  if (s.columns.some((c) => c.label)) {
    const hr = ws.addRow(s.columns.map((c) => c.label));
    hr.eachCell((cell, i) => {
      cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0B1324" } };
      cell.alignment = { horizontal: s.columns[i - 1]?.align === "right" ? "right" : "left" };
    });
  }
  for (const row of s.rows) {
    const r = ws.addRow(row.cells.map((c, i) => (c === null ? null : i === 0 && row.indent && typeof c === "string" ? c : c)));
    r.eachCell({ includeEmpty: true }, (cell, i) => {
      const col = s.columns[i - 1];
      if (col?.money || typeof cell.value === "number") cell.numFmt = col?.money ? '#,##0.00;[Red](#,##0.00);"-"' : "#,##0.##";
      cell.alignment = { horizontal: col?.align === "right" ? "right" : "left", indent: i === 1 && row.indent ? 2 : 0 };
      if (row.style === "heading") cell.font = { bold: true, color: { argb: "FF0E7490" } };
      if (row.style === "subtotal") {
        cell.font = { bold: true };
        cell.border = { top: { style: "thin", color: { argb: "FFCBD5E1" } } };
      }
      if (row.style === "total") {
        cell.font = { bold: true, size: 11 };
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFECFEFF" } };
        cell.border = { top: { style: "thin" }, bottom: { style: "double" } };
      }
      if (row.style === "note") cell.font = { italic: true, color: { argb: "FF94A3B8" } };
    });
  }
  if (s.notes?.length) {
    ws.addRow([]);
    for (const note of s.notes) {
      const r = ws.addRow([note]);
      ws.mergeCells(r.number, 1, r.number, n);
      r.font = { italic: true, size: 9, color: { argb: "FF64748B" } };
    }
  }
  const f = ws.addRow([`Generated by ${h.generatedBy} on ${new Date().toLocaleString("en-GB")} · OptiVault`]);
  ws.mergeCells(f.number, 1, f.number, n);
  f.font = { size: 8, color: { argb: "FF94A3B8" } };
  return Buffer.from(await wb.xlsx.writeBuffer());
}

export function toPdf(s: Statement, h: Header) {
  const doc = new jsPDF({ orientation: s.orientation ?? "portrait", unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 40;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(15, 23, 42);
  doc.text(h.orgName, margin, 50);
  doc.setFontSize(12);
  doc.setTextColor(14, 116, 144);
  doc.text(s.title, margin, 70);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(s.subtitle, margin, 85);

  const hasHead = s.columns.some((c) => c.label);
  autoTable(doc, {
    startY: 100,
    margin: { left: margin, right: margin, bottom: 50 },
    head: hasHead ? [s.columns.map((c) => c.label)] : undefined,
    body: s.rows.map((r) => r.cells.map((_, i) => (i === 0 && r.indent ? "    " : "") + cellText(s, r, i))),
    theme: "plain",
    styles: { font: "helvetica", fontSize: s.orientation === "landscape" ? 7.5 : 9.5, cellPadding: { top: 3, bottom: 3, left: 4, right: 4 }, textColor: [30, 41, 59] },
    headStyles: { fillColor: [11, 19, 36], textColor: [255, 255, 255], fontStyle: "bold" },
    columnStyles: Object.fromEntries(s.columns.map((c, i) => [i, { halign: c.align === "right" ? "right" : "left", ...(i === 0 && !hasHead ? { cellWidth: "auto" } : {}) }])),
    didParseCell: (d) => {
      if (d.section !== "body") return;
      const row = s.rows[d.row.index];
      if (row.style === "heading") {
        d.cell.styles.fontStyle = "bold";
        d.cell.styles.textColor = [14, 116, 144];
        d.cell.styles.cellPadding = { top: 9, bottom: 3, left: 4, right: 4 };
      } else if (row.style === "subtotal") {
        d.cell.styles.fontStyle = "bold";
        d.cell.styles.lineWidth = { top: 0.5, bottom: 0, left: 0, right: 0 };
        d.cell.styles.lineColor = [203, 213, 225];
      } else if (row.style === "total") {
        d.cell.styles.fontStyle = "bold";
        d.cell.styles.fillColor = [236, 254, 255];
        d.cell.styles.lineWidth = { top: 0.8, bottom: 1.2, left: 0, right: 0 };
        d.cell.styles.lineColor = [15, 23, 42];
      } else if (row.style === "note") {
        d.cell.styles.fontStyle = "italic";
        d.cell.styles.textColor = [148, 163, 184];
      }
      const v = row.cells[d.column.index];
      if (typeof v === "number" && v < 0) d.cell.styles.textColor = [225, 29, 72];
    },
  });

  let y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 18;
  if (s.notes?.length) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    for (const note of s.notes) {
      const lines = doc.splitTextToSize(note, pageW - margin * 2);
      doc.text(lines, margin, y);
      y += lines.length * 10 + 2;
    }
  }
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    const h2 = doc.internal.pageSize.getHeight();
    doc.text(`Generated by ${h.generatedBy} on ${new Date().toLocaleString("en-GB")} · OptiVault`, margin, h2 - 25);
    doc.text(`Page ${i} of ${pages}`, pageW - margin, h2 - 25, { align: "right" });
  }
  return Buffer.from(doc.output("arraybuffer"));
}
